name: Deploy GitHub Pages

on:
  push:
    branches:
      - main   # Löst den Workflow nur bei Pushes auf main aus

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: false   # Alte Builds werden nicht abgebrochen
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./           # Root-Ordner mit allen HTML-Dateien
          publish_branch: gh-pages  # Branch, auf den GitHub Pages deployed
